__title__ = 'crunch-global-leaderboard'
__description__ = 'crunch-global-leaderboard - Global Leaderboard core implementation for the CrunchDAO Platform'
__version__ = '0.1.1'
__author__ = 'Enzo CACERES'
__author_email__ = 'enzo.caceres@crunchdao.com'
__url__ = 'https://github.com/crunchdao/crunch-global-leaderboard'
